application: aandete
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /.*
  script: aandete.app

#skip_files: |
# ^bin/.*$|
# ^lib/python2.5/[^/]+$|
# ^(.*/)?(
# (app\.yaml)|
# (app\.yml)|
# (index\.yaml)|
# (index\.yml)|
# (#.*#)|
# (.*~)|
# (.*\.py[co])|
# (.*/RCS/.*)|
# (\..*)|
# )$
